name: yesh-web-teacher

env:
  DOCKER_REGISTRY: 590184137623.dkr.ecr.ap-southeast-1.amazonaws.com/yesh-web-teacher

on:
  workflow_dispatch:
    inputs:
      method:
        type: choice
        required: true
        description: Method
        default: build
        options:
          - build
          - deployment
          - build and deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code üõéÔ∏è
        if: ${{ github.event.inputs.method != 'deployment' }}
        uses: actions/checkout@v4

      - name: Set up Docker Buildx üöÄ
        if: ${{ github.event.inputs.method != 'deployment' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        if: ${{ github.event.inputs.method != 'deployment' }}
        id: login-ecr
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and push docker image (prod)
        if: ${{ github.event.inputs.method != 'deployment' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}:latest
            ${{ env.DOCKER_REGISTRY }}:${{ github.sha }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.method != 'build' }}
    steps:
      - name: Deployment
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout restart deployment teacher-frontend
